# docker-compose.override.yml (pour le développement)
 version: '3.8'
 services:
  frontend:
    build:
      target: development
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  api-gateway:
    volumes:
      - ./api-gateway/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
  user-service:
    volumes:
      - ./user-service/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
  order-service:
    volumes:
      - ./order-service/src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
  product-service:
    volumes:
      - ./product-service:/app
    environment:
      - FLASK_ENV=development
    command: python app/main.py